{%- set test_cases = cookiecutter.test_cases.split(" ") -%}
name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: {{ cookiecutter.slug }}

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v4
      - name: Run {% raw %}${{ matrix.command }}{% endraw %}
        run: make {% raw %}${{ matrix.command }}{% endraw %}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
{%- if cookiecutter.add_matrix == "y" %}
    strategy:
      matrix:
        instance:
{%- for instance in test_cases %}
          - {{ instance }}
{%- endfor %}
{%- endif %}
    defaults:
      run:
        working-directory: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
        with:
          path: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
{%- if cookiecutter.add_go_unit == "y" %}
      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." tests/go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: {% raw %}${{ env.GO_VERSION }}{% endraw %}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: {% raw %}${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}{% endraw %}
          restore-keys: |
            {% raw %}${{ runner.os }}-go-{% endraw %}
{%- endif %}
      - name: Compile component
{%-  if cookiecutter.add_matrix == "y" %}
        run: make test -e instance={% raw %}${{ matrix.instance }}{% endraw %}
{%- else %}
        run: make test
{%- endif %}
{%- if cookiecutter.add_golden == "y" %}
  golden:
    runs-on: ubuntu-latest
{%- if cookiecutter.add_matrix == "y" %}
    strategy:
      matrix:
        instance:
{%- for instance in test_cases %}
          - {{ instance }}
{%- endfor %}
{%- endif %}
    defaults:
      run:
        working-directory: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
        with:
          path: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
      - name: Golden diff
{%- if cookiecutter.add_matrix == "y" %}
        run: make golden-diff -e instance={% raw %}${{ matrix.instance }}{% endraw %}
{%- else %}
        run: make golden-diff
{%- endif %}
{%- endif %}
