name: Template tests
on:
  pull_request:
    branches:
    - main
    paths:
      - '{{ cookiecutter.slug }}/**'
      - 'hooks/**'

jobs:
  test-rendered:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        add_lib:
          - "n"
          - "y"
        add_pp:
          - "n"
          - "y"
        add_golden:
          - "n"
          - "y"
        add_matrix:
          - "n"
          - "y"
        add_go_unit:
          - "n"
          - "y"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - name: Run lint
        run: make test -e cruft_extra_content='{"slug":"test-component","name":"test-component","add_lib":"${{matrix.add_lib}}","add_pp":"${{matrix.add_pp}}","add_golden":"${{matrix.add_golden}}","add_matrix":"${{matrix.add_matrix}}","add_go_unit":"${{matrix.add_go_unit}}"}'
      - name: Run golden-diff
        if: ${{ matrix.add_golden == 'y' }}
        run: |
          cd test-component
          make golden-diff -e git_volume=
  test-rendered-test-cases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        add_golden:
          - "n"
          - "y"
        test_cases:
          - "defaults"
          - "defaults foo"
          - "foo bar"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: Gr1N/setup-poetry@v8
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: poetry install
    - name: Run lints
      run: |
        make render -e cruft_extra_content='{"slug":"test-component","name":"test-component","add_golden":"${{matrix.add_golden}}","test_cases":"${{matrix.test_cases}}"}'
        for t in ${{matrix.test_cases}}; do
          test -f test-component/tests/${t}.yml
        done
    - name: Run golden-diff-all
      if: ${{ matrix.add_golden == 'y' }}
      run: |
        cd test-component
        make -j1 golden-diff-all -e git_volume=
